services:
  database:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@database/postgres?sslmode=disable'
    depends_on:
      - database
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: 'http://backend:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
