services:
  database:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: todo
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    ports:
      - '${HTTP_PORT:-3000}:${HTTP_PORT:-3000}'
    environment:
      DATABASE_URL: 'postgres://postgres:${POSTGRES_PASSWORD:-postgres}@database/postgres?sslmode=disable'
      HTTP_PORT: ${HTTP_PORT:-3000}
    depends_on:
      - database
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: 'http://backend:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
